# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dartmouth CS52 â€” 16X
tagline: Full-Stack Web Development
email: tim@zingweb.com
# About/contact
author:
  name:       Tim Tregubov
  url:        "http://www.zingweb.com"
description: > # this means to ignore newlines until "baseurl:"
  Full-Stack Web Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dartmouth-cs52.github.io" # the base hostname & protocol for your site
twitter_username: timofei7
github_username:  timofei7

# Build settings
markdown: kramdown

gems:
  - jemoji
